name: Deploy Auth Inbox to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Deploy Auth Inbox Worker
    steps:
      # 步骤 1: 检出代码
      - name: Checkout Repository
        uses: actions/checkout@v6

      # 步骤 2: 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
      
      # 步骤 3: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24' # 根据您的项目需求选择 Node.js 版本
          cache: 'pnpm' #设置pnpm缓存

      # 步骤 4: 安装依赖项
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      # 步骤 5: 构建前端
      - name: Build Web App
        run: pnpm --filter auth-inbox-web run build

      # 步骤 6: 写入wrangler.toml
      - name: write wrangler.toml
        run: echo "$WRANGLER_TOML" > wrangler.toml
        env:
          WRANGLER_TOML: ${{ secrets.TOML }}

      # 步骤 7: 部署 Worker
      - name: Deploy Backend for ${{ github.ref_name }}
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            FrontEndAdminID
            FrontEndAdminPassword
            AI_BASE_URL
            AI_API_KEY
            AI_API_FORMAT
            AI_MODEL
        env:
          FrontEndAdminID: ${{ secrets.FrontEndAdminID }}
          FrontEndAdminPassword: ${{ secrets.FrontEndAdminPassword }}
          AI_BASE_URL: ${{ secrets.AI_BASE_URL }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          AI_API_FORMAT: ${{ secrets.AI_API_FORMAT }}
          AI_MODEL: ${{ secrets.AI_MODEL }}